export const KEYCLOAK_CLIENT = {
  id: 'ae457880-587e-462c-b4c4-6705f9eea433',
  clientId: 'rides-backend',
  name: 'Ride Backend',
  description: 'The rides backend builded with nestJS',
  rootUrl: '',
  adminUrl: '',
  baseUrl: '',
  surrogateAuthRequired: false,
  enabled: true,
  alwaysDisplayInConsole: false,
  clientAuthenticatorType: 'client-secret',
  secret:
    process.env.KEYCLOAK_CLIENT_SECRET ||
    'c7b3b3b3-0b7b-4b3b-8b3b-3b7b3b3b3b3b',
  redirectUris: ['/*'],
  webOrigins: ['*', 'server:8000/*', 'http://localhost:8000/*'],
  notBefore: 0,
  bearerOnly: false,
  consentRequired: false,
  standardFlowEnabled: false,
  implicitFlowEnabled: false,
  directAccessGrantsEnabled: true,
  serviceAccountsEnabled: true,
  authorizationServicesEnabled: true,
  publicClient: false,
  frontchannelLogout: true,
  protocol: 'openid-connect',
  attributes: {
    realm_client: 'false',
    'oidc.ciba.grant.enabled': 'false',
    'client.secret.creation.time': '1732587992',
    'backchannel.logout.session.required': 'true',
    'oauth2.device.authorization.grant.enabled': 'false',
    'backchannel.logout.revoke.offline.tokens': 'false',
  },
  authenticationFlowBindingOverrides: {},
  fullScopeAllowed: true,
  nodeReRegistrationTimeout: -1,
  protocolMappers: [
    {
      id: 'a89fde4b-644d-429c-bfae-b7db6d835b9a',
      name: 'Client ID',
      protocol: 'openid-connect',
      protocolMapper: 'oidc-usersessionmodel-note-mapper',
      consentRequired: false,
      config: {
        'user.session.note': 'client_id',
        'id.token.claim': 'true',
        'introspection.token.claim': 'true',
        'access.token.claim': 'true',
        'claim.name': 'client_id',
        'jsonType.label': 'String',
      },
    },
    {
      id: '1a4cc4e1-e04c-43a2-afdb-9c3d441ae1c6',
      name: 'Client Host',
      protocol: 'openid-connect',
      protocolMapper: 'oidc-usersessionmodel-note-mapper',
      consentRequired: false,
      config: {
        'user.session.note': 'clientHost',
        'id.token.claim': 'true',
        'introspection.token.claim': 'true',
        'access.token.claim': 'true',
        'claim.name': 'clientHost',
        'jsonType.label': 'String',
      },
    },
    {
      id: 'b9b3d0dc-ff78-4195-a7e9-b35d95bea1b6',
      name: 'Client IP Address',
      protocol: 'openid-connect',
      protocolMapper: 'oidc-usersessionmodel-note-mapper',
      consentRequired: false,
      config: {
        'user.session.note': 'clientAddress',
        'id.token.claim': 'true',
        'introspection.token.claim': 'true',
        'access.token.claim': 'true',
        'claim.name': 'clientAddress',
        'jsonType.label': 'String',
      },
    },
  ],
  defaultClientScopes: [
    'web-origins',
    'acr',
    'roles',
    'profile',
    'basic',
    'email',
  ],
  optionalClientScopes: [
    'address',
    'phone',
    'organization',
    'offline_access',
    'microprofile-jwt',
  ],
  authorizationSettings: {
    allowRemoteResourceManagement: true,
    policyEnforcementMode: 'ENFORCING',
    resources: [
      {
        name: 'Default Resource',
        type: 'urn:rides-backend:resources:default',
        ownerManagedAccess: false,
        attributes: {},
        uris: ['/*'],
      },
    ],
    policies: [],
    scopes: [],
    decisionStrategy: 'UNANIMOUS',
  },
};
