name: Coverage Report

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest

    env:
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_HOST: ${{ secrets.DB_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage (Server)
        run: |
          cd server
          npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: server/coverage/coverage-final.json
          flags: backend
          fail_ci_if_error: true
          verbose: true
